### ISSUE TITLE
Block Option No Longer Available

### ISSUE THREAD

**Issue by HaChamor** [damianmgarcia/Hide-n-Seek#17]
Hello,

I downloaded your Hide n" Seek extension about ten days ago. It was a dream, using it. I was blocking many organizations/jobs, as most I was not suited for. It made the work of looking for a job sooooo much easier. After about a week, though, the red icon that I used to click on to clear the entry disappeared. The search function for both Indeed and LinkedIn still work, which is also just as great.

I've removed the extension, hoping to get the blocking feature back. No go. I've cleared Chrome's cache and re-downloaded it, but still nogo. Might there be any other information you'd need from me to possibly trace this problem... if it's a problem at all.  :-)

Tim

**Comment by damianmgarcia** [comment]
Hi Tim,

I'm so sorry you ran into this issue. I'm going to look into it and try my best to fix it.

Are the block buttons missing on both LinkedIn and Indeed, or just one of them?

Thank you

**Comment by damianmgarcia** [comment]
I am seeing this issue with Indeed -- the block buttons are missing. However, I can still see the block buttons on LinkedIn.

It appears that Indeed updated some of their code and renamed a few things that Hide n' Seek normally looks for to detect job listings.

I'm working on a fix right now and I hope it will address your issue. However, it's possible that your issue is caused by something else, and we may have to continue troubleshooting later.

Thanks again for reporting this!

**Comment by damianmgarcia** [comment]
I released the update, version 4.2.3 (#18 ), and it is currently under review by the Chrome Web Store. It usually takes a few days for them to complete their review before the update gets published.

Again, I'm not sure if this fix will address the issue you are having, but if it doesn't, I'll continue trying to figure out what is causing it.

**Comment by HaChamor** [comment]
Thank you for your response. I'll be watching for the update to come through. I'll let you know what happens.

“There are but few important events in the affairs of men brought about by their own choice.” ~~ Ulysses S. Grant

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by damianmgarcia** [comment]
**I am so happy to hear that!**

I will leave this issue open for comment for another day or two, just in case.

_**Thank you so much for bringing this issue to my attention.**_
