### ISSUE TITLE
Is there a way to automatically hide applied jobs?

### ISSUE THREAD

**Issue by yanrs17** [damianmgarcia/Hide-n-Seek#26]
It's quite annoying Linkedin does not automatically hide jobs you have applied.

**Comment by yanrs17** [comment]
<img width="114" alt="image" src="https://github.com/damianmgarcia/Hide-n-Seek/assets/18586504/7ccdd62d-80c9-4a41-9f49-05dca06dcd5f">
Or can I click on X on the top-right then this specific job is also hidden?

**Comment by damianmgarcia** [comment]
Hi, and thank you for your question!

First, just to be clear for future readers who may not know this, the "X" that Ryan is referring to is NOT a part of Hide n' Seek. That X is a button built-in by LinkedIn and you'll see it on every listing. I believe the purpose of the X is not simply to hide that job, but to teach the LinkedIn search algorithm that you're not interested in jobs like that, so you may want to be careful when using it.

Second, Hide n' Seek does not currently support hiding jobs that users have applied to. However, when time allows, I will consider the possibility of implementing it for LinkedIn and Indeed.

Thank you!

**Comment by yanrs17** [comment]
Thanks!

**Comment by liubq7** [comment]
Would love to have this feature too!
