### ISSUE TITLE
Wrong company name blocked

### ISSUE THREAD

**Issue by damianmgarcia** [damianmgarcia/Hide-n-Seek#32]
The below is a bug report by Matej from their Chrome Web Store review. Thanks Matej!

> I think LinkedIn may have changed how jobs are named. 
> 
> Filtering before: *presses on red circle* filter applied on "Adecco"
> Filtering now:      *presses on red circle* filter applied on "Adecco · Zurich, Zurich, Switzerland (On-site)"
> 
> There is always " · " as separator, detecting that might fix the issue.

**Comment by Matej9937** [comment]
Hi Damian, this is Matej from the Chrome Web Store review.
Thank you for your reply and for looking into it.

I am sending a screenshot. If there is something else I could do, let me know. I would be happy to help.
![image](https://github.com/user-attachments/assets/9a3b4f97-90df-429f-a1b7-bcfb6e3a7e58)

**Comment by damianmgarcia** [comment]
Wonderful, this is excellent! It looks like they are doing A/B testing. I can see from your screenshots that LinkedIn slightly changed the layout, where the company name and location are separated by a middle dot, as you pointed out earlier.

I would like to update the extension so that it can detect this new layout, and would appreciate some more of your help, if you don't mind. :)

Basically, it would be helpful if I could see the HTML code of the job listings so that I can see what LinkedIn changed. I made a short 1-minute video that shows how to capture the job listings code: https://drive.google.com/file/d/1A5BND6l5ozEim4C7uByXZ8n0x58Z0zEk/view?usp=sharing

If you're able to get a copy of the code that holds the job listings by following along with the video, you can paste the code in a TXT file, save it, and then email it to me (damian at outlook dot com), or you can share it via your preferred cloud storage service, like Google Docs, etc.

The steps in the video are:

1. Click Chrome's menu button to open the main menu
2. Go to "More tools" and then click "Developer tools"
3. In the developer tools window that pops up, click the "Elements" tab
4. Click the icon in the top-left corner or the developer tools window that looks like a dotted square with an arrow going into it. When you click it, you should see that the icon color changes to blue.
5. Then mouse over to the scroll bar that's used to scroll through the listings. You should see that the scroll bar turns green and the listings turn blue as you hover over the scroll bar. Click the scroll bar (it doesn't matter where exactly you click it).
6. After you click the scroll bar, go to the highlighted element in the developer tools and click the "..." to the left of it to open its menu
7. Go to "Copy" and then click "Copy element"
8. Paste the code in a TXT file, save it, and then email it to me (damian at outlook dot com), or you can share it via your preferred cloud storage service, like Google Docs, etc.

Thank you so much for your help! :)

**Comment by damianmgarcia** [comment]
This issue is resolved in version 5.0.1, which has been sent to Chrome Web Store, etc., for review. The review process usually takes 1-3 days. I'll update this thread once the new version has been published to the Chrome Web Store.

Thanks so much for bringing this issue to my attention and for all of your help @Matej9937! Your support was critical in resolving this issue!
