### ISSUE TITLE
how to hide companies?

### ISSUE THREAD

**Issue by merlinlearnscode** [damianmgarcia/Hide-n-Seek#39]
hello, how do i hide companies using this extension maybe im just blind and cant see the control but please help

**Comment by damianmgarcia** [comment]
Hello!

Thanks for trying out Hide n' Seek!

With the extension installed, you should see "block" buttons next to jobs listings on LinkedIn, Indeed, and Glassdoor. Clicking a "block" button blocks all jobs by the company that listed that job. Here's an example of what LinkedIn listings looks like with the "block" buttons:

<img width="878" alt="Screenshot 2024-10-08 194430" src="https://github.com/user-attachments/assets/7a270c1a-ecb1-459a-b5c4-9f05ea1d4ab5">

Are you seeing the "block" buttons next to the job listings? If so, just click that button and that will hide all the jobs by that company. If you don't want the blocked companies to be visible on the page, you can turn on the "Do not display hidden jobs" option in the popup.

<img width="881" alt="Screenshot 2024-10-08 195035" src="https://github.com/user-attachments/assets/cdf6d582-be67-4db7-bae2-be22e9fb8493">

There's also a guide here: https://github.com/damianmgarcia/Hide-n-Seek?tab=readme-ov-file#usage

**However, if you do not see the block buttons, there may be something else going on, so please let me know if that's the case!**

Thank you!

**Comment by damianmgarcia** [comment]
Hi @merlinlearnscode, I hope that you're doing well!

If you still need any help, please let me know, but otherwise I'll close this issue in a couple of days since it's been almost 2 weeks without a response.

Take care
