### ISSUE TITLE
Firefox LinkedIn Blocking appears broken

### ISSUE THREAD

**Issue by alexmerm** [damianmgarcia/Hide-n-Seek#44]
If I try to block any company in the LinkedIn Job search on Firefox it shows up at "Unknown company" and ends up blocking all of the listings show. It also isn't blocking the previously blocked jobs. It worked fine as of last week but noticed an issue today. I tested with a fresh install on a different and the issue persisted. However, on Chrome, it appears to work fine. Also not sure if this is contributing to this error, but it looks like the Firefox Add-On version of this extension is still on version 4.3.3, while the chrome is on 5.1.0

**Comment by damianmgarcia** [comment]
Thanks so much for reporting this issue! I released a new version (5.1.1) to the Firefox addons store. If you have time, can you please update Hide n' Seek and see if the update fixed the issue for you? To manually update, you can go to about:addons in the URL bar, then click the button with the gear icon, and then select "Check for Updates" from the menu.

Take care! :)

**Comment by alexmerm** [comment]
It's fixed! thanks for getting to this so fast :)
